### ISSUE TITLE
Is not correctly displayed on High Sierra

### ISSUE THREAD

**Issue by marselle-tesla** [insidegui/GRCustomizableWindow#7]
![2017-10-11 3 42 00](https://user-images.githubusercontent.com/20689286/31417106-30a95fbc-ae36-11e7-80a3-8e0cf23731ac.png)
Hi, the window on High Sierra is not correctly displayed.
Please fix.
Thank you.

**Comment by insidegui** [comment]
Sorry, I am not actively developing this project anymore. There are better ways to make custom windows on modern macOS (check https://github.com/insidegui/WWDC/blob/master/WWDC/WWDCWindow.swift for an example).

I would happily accept a PR if anyone is interested in making one.

**Comment by marselle-tesla** [comment]
I already solved this problem. Thank you
If someone needs:
1) replace 
`self.leatherWindow.titleColor = [NSColor  whiteColor];`
 to 
`self.leatherWindow.titleColor = [NSColor  colorWithCalibratedWhite:1.0 alpha:1.0];`
2) in IB check "Hide title" of window


![2017-10-11 17 28 40](https://user-images.githubusercontent.com/20689286/31447031-abc2c206-aea9-11e7-9954-33dfb2643e69.png)

**Comment by insidegui** [comment]
Awesome! That looks great. Thanks for sharing.
